=== GabrielMindev/XML-project/project/src/GameCatalogue.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT catalogue (Game+,Publisher+)>
<!ELEMENT Game (Name,Platforms,Information,Genre,Price,ReleaseDate,BuyLink,CoverImageLink)>
<!ATTLIST Game
    publisher CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Platforms (platform_type)+>
<!ELEMENT platform_type (#PCDATA)>
<!ELEMENT Information (#PCDATA)>
<!ELEMENT Genre (genre_type)+>
<!ELEMENT genre_type (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price
    currency CDATA #IMPLIED>
<!ELEMENT ReleaseDate (#PCDATA)>
<!ELEMENT BuyLink (#PCDATA)>
<!ELEMENT CoverImageLink EMPTY>
<!ATTLIST CoverImageLink
    alt CDATA #REQUIRED
    src CDATA #REQUIRED>
<!ELEMENT Publisher (name,founded,address?,numberOfEmployees,president,publisherWebSiteURL)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT founded (#PCDATA)>
<!ELEMENT address (street,country,zip_code)>
<!ELEMENT numberOfEmployees (#PCDATA)>
<!ELEMENT president (#PCDATA)>
<!ELEMENT publisherWebSiteURL (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT country (city)>
<!ATTLIST country
    name  CDATA #REQUIRED>
<!ELEMENT zip_code (#PCDATA)>
<!ELEMENT city (#PCDATA)>

=== GabrielMindev/XML-project/project/src/GameCatalogue1.xml
<?xml version="1.0" encoding="UTF-8"?>


<?xml-stylesheet type="text/xsl" href="XmlToHTML4.xsl"?>
<!DOCTYPE catalogue SYSTEM "GameCatalogue.dtd">
<catalogue >

    <Game publisher="EA studios">
        <Name>FIFA 21</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>
            Време е за стартиране. Създайте своя отбор и спечелете пътя си до върха на дивизията във FIFA 21. Водете своя отбор до победа в режим на кампания или се състезавайте с приятели в FIFA Ultimate Team. Съберете се на улицата или на стадиона и се насладете на по-големи победи с приятелите си. FIFA 21 ще предложи двойни права, така че можете да получите безплатно надграждане до ретроспективната конзола от следващо поколение  </Information>
        <Genre>
            <genre_type>Спорт</genre_type>
        </Genre>
        <Price currency="евро">29.59</Price>
        <ReleaseDate>5-10-2020</ReleaseDate>
        <BuyLink>https://store.steampowered.com/app/1313860/EA_SPORTS_FIFA_21/</BuyLink>
        <CoverImageLink alt="FIFA 21 Cover" src="fifa21"/>
    </Game>

    <Game publisher="Epic Games">
        <Name>Fortnite: Battle Royale</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>Fortnite Battle Royale е БЕЗПЛАТНИЯ PvP режим от 100 играчи във Fortnite. Една гигантска карта. Боен автобус. Умения за изграждане на Fortnite и разрушима среда, съчетана с интензивна PvP битка. Печели последният, който остане.</Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>FPS</genre_type>
            <genre_type>Мултиплейър</genre_type>
        </Genre>
        <Price>Free</Price>
        <ReleaseDate>21-07-2017</ReleaseDate>
        <BuyLink>https://www.epicgames.com/fortnite/en-US/buy-now/battle-royale</BuyLink>
        <CoverImageLink alt="Fortnite Cover" src="fortnite"/>
    </Game>

    <Publisher>
        <name>Epic Games</name>
        <founded>1991</founded>
        <address>
            <street>"620 булевард Кросроудс "</street>
            <country name="САЩ">
                <city>Кари</city>
            </country>
            <zip_code>NC 27518</zip_code>
        </address>
        <numberOfEmployees>700</numberOfEmployees>
        <president>Тим Суинии</president>
        <publisherWebSiteURL>https://www.epicgames.com/</publisherWebSiteURL>
    </Publisher>

    <Publisher>
        <name>EA Studios</name>
        <founded>1982</founded>
        <address>
            <street>"Редууд Шорс Паркуей"</street>
            <country name="САЩ">
                <city>Редууд</city>
            </country>
            <zip_code>CA 94065</zip_code>
        </address>
        <numberOfEmployees>9300</numberOfEmployees>
        <president>Трип Хоукинс</president>
        <publisherWebSiteURL>https://www.ea.com/ea-studios</publisherWebSiteURL>
    </Publisher>


</catalogue>

=== GabrielMindev/XML-project/project/src/GameCatalogue2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XmlToXml1.xsl"?>
<!DOCTYPE catalogue SYSTEM "GameCatalogue.dtd">

<catalogue>
    <Game publisher="Rockstar Games">
        <Name>Grand Theft Auto V</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>
            Най-големият, най-динамичен и най-разнообразен отворен свят, създаван някога, Grand Theft Auto V съчетава разказването на истории и геймплея по нови начини, тъй като играчите многократно скачат и излизат от живота на тримата водещи герои на играта, играейки всички страни на преплетената история на играта. Всички класически отличителни белези на новаторската поредица се връщат, включително невероятно внимание към детайла и тъмно хумористичното възприемане на Grand Theft Auto от модерната култура, заедно с чисто нов и амбициозен подход за мултиплейър с отворен свят. </Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>Приключенски</genre_type>
            <genre_type>Мултиплейър</genre_type>
            <genre_type>Ролева</genre_type>
        </Genre>
        <Price currency="лева">50</Price>
        <ReleaseDate>17-09-2013</ReleaseDate>
        <BuyLink>https://www.rockstargames.com/V/order</BuyLink>
        <CoverImageLink alt="GTA V Cover" src ="gtaV_pic"/>
    </Game>

    <Game publisher="Rockstar Games">
        <Name>Red Dead Redemption 2</Name>
        <Platforms >
            <platform_type>Xbox One</platform_type>
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>Америка, 1899 г. Краят на ерата на Дивия Запад започна. След като обир се обърква зле в западния град Блекуотър, Артър Морган и бандата на Ван дер Линде са принудени да избягат. С федерални агенти и най-добрите ловци на глави в страната, които се натрупват по петите, бандата трябва да ограби, открадне и да се пребори през суровата сърцевина на Америка, за да оцелее. Тъй като задълбочаващите се вътрешни разделения заплашват да разкъсат бандата, Артър трябва да направи избор между собствените си идеали и лоялността към бандата, която го е отгледала. </Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>Приключенски</genre_type>
            <genre_type>Ролева</genre_type>
        </Genre>
        <Price currency="US долари">59.99</Price>
        <ReleaseDate>26-10-2018</ReleaseDate>
        <BuyLink>https://www.rockstargames.com/reddeadredemption2/order</BuyLink>

        <CoverImageLink alt="RDR2 Cover" src="rdr2_pic"/>
    </Game>

    <Publisher>
        <name>Rockstar Games</name>
        <founded>1998</founded>
        <address>
            <street>"622 Броудуей"</street>
            <country name="САЩ">
                <city>Ню Йорк</city>
            </country>
            <zip_code>NY 10012</zip_code>
        </address>
        <numberOfEmployees>2001</numberOfEmployees>
        <president>Сам Хаусър</president>
        <publisherWebSiteURL>https://www.rockstargames.com/</publisherWebSiteURL>
    </Publisher>

</catalogue>

=== GabrielMindev/XML-project/project/src/GameCatalogue5.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XmlToText2.xsl"?>
<!DOCTYPE catalogue SYSTEM "GameCatalogue.dtd">
<catalogue>
    <Game publisher="CD Projekt">
        <Name>Cyberpunk 2077</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
            <platform_type>Xbox Series X</platform_type>
            <platform_type>Xbox Series S</platform_type>
            <platform_type>PS4</platform_type>
            <platform_type>PS5</platform_type>
        </Platforms>
        <Information>Cyberpunk 2077 е ролева игра за 2020 г., разработена и публикувана от CD Projekt. Историята се развива в Night City, отворен свят, разположен във вселената на Cyberpunk. Играчите приемат перспективата от първо лице на персонализиран наемник, известен като V, който може да придобие умения за хакване и машини с опции за меле и дистанционна битка. </Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>Ролева</genre_type>
        </Genre>
        <Price currency="евро">59.99</Price>
        <ReleaseDate>10-12-2020</ReleaseDate>
        <BuyLink>https://store.steampowered.com/agecheck/app/1091500/</BuyLink>
        <CoverImageLink alt="Cyberpunk 2077 Cover" src="Cyberpunk2077_pic"/>
    </Game>

    <Game publisher="Santa Monica">
        <Name>God of War 4</Name>
        <Platforms >
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>God of War е приключенски-екшън от трето лице. Той разполага със свободна камера през рамо, отклонение от предишните части на играта, които включваха фиксирана кинематографична камера (с изключение на двуизмерния страничен скролер Betrayal). Кинематографично, играта се представя в непрекъснат кадър, без разрязване на камерата или зареждане на екрани </Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>Приключенски</genre_type>
        </Genre>
        <Price currency="лева">59.90</Price>
        <ReleaseDate>20-04-2018</ReleaseDate>
        <BuyLink>https://www.playstation.com/bg-bg/games/god-of-war/</BuyLink>
        <CoverImageLink alt="God of War 4 Cover" src="GodofWar4_pic"/>
    </Game>

    <Publisher>
        <name>CD Projekt</name>
        <founded>1994</founded>
        <address>
            <street>"Жагиеллонска 74"</street>
            <country name="Полша">
                <city>Варшава</city>
            </country>
            <zip_code>03-301</zip_code>
        </address>
        <numberOfEmployees>1111</numberOfEmployees>
        <president>Марцин Туински</president>
        <publisherWebSiteURL>https://www.cdprojekt.com/pl/</publisherWebSiteURL>
    </Publisher>

    <Publisher>
        <name>Santa Monica</name>
        <founded>1999</founded>
        <address>
            <street>"булевард Джеферсън"</street>
            <country name="САЩ">
                <city>Лос Анджълис</city>
            </country>
            <zip_code>CA 90094</zip_code>
        </address>
        <numberOfEmployees>200</numberOfEmployees>
        <president>Алан Бекер</president>
        <publisherWebSiteURL>https://sms.playstation.com/</publisherWebSiteURL>
    </Publisher>
</catalogue>

=== GabrielMindev/XML-project/project/src/GameCatalogue3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XmlToXml2.xsl"?>
<!DOCTYPE catalogue SYSTEM "GameCatalogue.dtd">
<catalogue>
    <Game publisher="Microsoft Studios">
        <Name>Forza Motorsport 7</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
        </Platforms>
        <Information>Forza Motorsport 7 е състезателна видео игра с над 700 автомобила - включително нови автомобили Forza Edition, повечето от които са донесени от Forza Horizon 3 и повече от 200 различни конфигурации, за да се състезават на 32 места при старта, включително всички от Forza Motorsport 6; измислена улична верига в Дубай е една от новите писти и няколко писти, които се връщат от Forza Motorsport 4, включително Maple Valley Raceway, Mugello Circuit и Suzuka Circuit. Две функции, които са нови за заглавието на Motorsport, включват динамично време (по-рано се вижда в заглавията на Horizon) и персонализиращи се драйвери.</Information>
        <Genre>
            <genre_type>Състезания</genre_type>
        </Genre>
        <Price currency="лева">57.40</Price>
        <ReleaseDate>03-10-2017</ReleaseDate>
        <BuyLink>https://www.microsoft.com/bg-bg/p/forza-motorsport-7-ultimate-edition/9nv34nlclg81?activetab=pivot:overviewtab</BuyLink>
        <CoverImageLink alt="Forza Horizon 4 Cover" src="forza_pic"/>
    </Game>

    <Game publisher="EA Studios">
        <Name>Need For Speed Heat</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>Xbox One</platform_type>
        </Platforms>
        <Information>
            Бързайте през деня и рискувайте всичко през нощта в Need for Speed Heat Deluxe Edition, състезателна игра, в която линиите на закона избледняват, когато слънцето започне да залязва. </Information>
        <Genre>
            <genre_type>Състезания</genre_type>
        </Genre>
        <Price currency="евро">20.99</Price>
        <ReleaseDate>08-11-2019</ReleaseDate>
        <BuyLink>https://store.steampowered.com/app/1222680/Need_for_Speed_Heat/</BuyLink>
        <CoverImageLink alt="Need For Speed Heat Cover" src="nfs_pic"/>
    </Game>


    <Publisher>
        <name>Microsoft Studios</name>
        <founded>2002</founded>
        <address>
            <street>"148th Авеню "</street>
            <country name="САЩ">
                <city>Редмонд</city>
            </country>
            <zip_code>WA 98052</zip_code>
        </address>
        <numberOfEmployees>4000</numberOfEmployees>
        <president>Фил Спенсър</president>
        <publisherWebSiteURL>https://www.microsoftstudios.com/</publisherWebSiteURL>
    </Publisher>

    <Publisher>
        <name>EA Studios</name>
        <founded>1982</founded>
        <address>
            <street>"Редууд Шорс Паркуей"</street>
            <country name="САЩ">
                <city>Редууд</city>
            </country>
            <zip_code>CA 94065</zip_code>
        </address>
        <numberOfEmployees>9300</numberOfEmployees>
        <president>Трип Хоукинс</president>
        <publisherWebSiteURL>https://www.ea.com/ea-studios</publisherWebSiteURL>
    </Publisher>

</catalogue>

=== GabrielMindev/XML-project/project/src/GameCatalogue4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XmlToHTML2.xsl"?>
<?xml-stylesheet type="text/xsl" href="XmlToText1.xsl"?>
<!DOCTYPE catalogue SYSTEM "GameCatalogue.dtd">
<catalogue>
    <Game publisher="Ubisoft">
        <Name>Assassin's Creed Valhalla</Name>
        <Platforms >
            <platform_type>PC</platform_type>
            <platform_type>PS5</platform_type>
            <platform_type>Xbox One</platform_type>
            <platform_type>PS4</platform_type>
        </Platforms>
        <Information>Assassin's Creed Valhalla е екшън ролева видео игра, разработена от Ubisoft Montreal и публикувана от Ubisoft.
                     Това е дванадесетата основна част и двадесет и второто издание от серията Assassin's Creed и наследник на Assassin's Creed Odyssey от 2018 г. </Information>
        <Genre>
            <genre_type>Екшън</genre_type>
            <genre_type>Приключенски</genre_type>
            <genre_type>Ролева</genre_type>
        </Genre>
        <Price currency="US долари">49.79</Price>
        <ReleaseDate>10-10-2020</ReleaseDate>
        <BuyLink>https://store.ubi.com/us/assassins-creed-valhalla/5e849c6c5cdf9a21c0b4e731.html?lang=en_US</BuyLink>
        <CoverImageLink alt="Assassin's Creed Valhalla Cover" src="AC_pic"/>
    </Game>

    <Game publisher="SCS Software">
        <Name>Euro Truck Simulator 2</Name>
        <Platforms>
            <platform_type>PC</platform_type>
        </Platforms>
        <Information>Играта е директно продължение на играта Euro Truck Simulator от 2008 г. и е втората видео игра от поредицата Truck Simulator.
                     Основната идея на играта е, че играчът може да кара един от избраните съчленени камиони през цяла Европа, да взима товари от различни места и да ги доставя. </Information>
        <Genre>
            <genre_type>Симулатор</genre_type>
            <genre_type>Мълтиплейър</genre_type>
        </Genre>
        <Price currency="евро">19.99</Price>
        <ReleaseDate>19-10-2012</ReleaseDate>
        <BuyLink>https://store.steampowered.com/app/227300/Euro_Truck_Simulator_2/?l=bulgarian</BuyLink>
        <CoverImageLink alt="Euro Truck Simulator 2 Cover" src="euro_truck"/>
    </Game>

    <Publisher>
        <name>Ubisoft</name>
        <founded>1986</founded>
        <address>
            <street>"28 Рю Арманд Карел"</street>
            <country name="Франция">
                <city>Монтревил</city>
            </country>
            <zip_code>93100</zip_code>
        </address>
        <numberOfEmployees>18045</numberOfEmployees>
        <president>Ивес Гуйлемот</president>
        <publisherWebSiteURL>https://www.ubisoft.com/</publisherWebSiteURL>
    </Publisher>

    <Publisher>
        <name>SCS Software</name>
        <founded>1997</founded>
        <address>
            <street>"Жихлавска"</street>
            <country name="Чехия">
                <city>Прага</city>
            </country>
            <zip_code>140 00</zip_code>
        </address>
        <numberOfEmployees>170</numberOfEmployees>
        <president>Павел Себор</president>
        <publisherWebSiteURL>https://scssoft.com/</publisherWebSiteURL>
    </Publisher>
</catalogue>
